version: '3.2'
services:
  front:
    container_name: front
    build: ./reused-modules-front
    volumes:
      - ./reused-modules-front/:/app/
      - /app/node_modules
    command: pnpm dev
    ports:
      - '3000:3000'

  api:
    container_name: api
    build: ./reused-modules-api
    volumes:
      - ./reused-modules-api/:/app/
    ports:
      - '8081:8080'

  cms:
    container_name: cms
    build: ./reused-modules-cms
    volumes:
      - ./reused-modules-cms/:/app/
      - /app/node_modules
    command: pnpm dev
    ports:
      - '6000:6000'

  db-mysql:
    container_name: db-mysql
    image: mysql:8
    volumes:
      - ./docker/db/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 33061:3306
